export type Resturant = {
    name: string,
    distance: number,
    hasLuxuryPricerange: boolean,
    hasMediumPricerange: boolean,
    hasPoorPricerange: boolean,
    hasMeat: boolean,
    hasBurger: boolean,
    hasSushi: boolean,
    hasVeg: boolean,
    hasPizza: boolean,
    hasFish: boolean
}
export const resturants: Resturant[] = [
    {
        name: "Sen Kitchen",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: true,
        hasPoorPricerange: false,
        hasBurger: false,
        hasFish: false,
        hasMeat: true,
        hasPizza: false,
        hasSushi: false,
        hasVeg: true
    },
    {
        name: "McDonalds",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: false,
        hasPoorPricerange: true,
        hasBurger: true,
        hasFish: false,
        hasMeat: true,
        hasPizza: false,
        hasSushi: false,
        hasVeg: true
    },
    {
        name: "Holy Greens",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: true,
        hasPoorPricerange: false,
        hasBurger: false,
        hasFish: false,
        hasMeat: false,
        hasPizza: false,
        hasSushi: false,
        hasVeg: true
    },
    {
        name: "Wokhouse",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: false,
        hasPoorPricerange: true,
        hasBurger: false,
        hasFish: false,
        hasMeat: true,
        hasPizza: false,
        hasSushi: false,
        hasVeg: true
    },
    {
        name: "The Fishery",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: true,
        hasPoorPricerange: false,
        hasBurger: true,
        hasFish: true,
        hasMeat: false,
        hasPizza: false,
        hasSushi: false,
        hasVeg: true
    },
    {
        name: "K25",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: true,
        hasPoorPricerange: false,
        hasBurger: true,
        hasFish: true,
        hasMeat: true,
        hasPizza: false,
        hasSushi: true,
        hasVeg: true
    },
    {
        name: "Barrels",
        distance: 0,
        hasLuxuryPricerange: true,
        hasMediumPricerange: false,
        hasPoorPricerange: false,
        hasBurger: true,
        hasFish: false,
        hasMeat: true,
        hasPizza: false,
        hasSushi: false,
        hasVeg: false
    },
    {
        name: "GUTE",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: true,
        hasPoorPricerange: false,
        hasBurger: false,
        hasFish: false,
        hasMeat: true,
        hasPizza: false,
        hasSushi: false,
        hasVeg: false
    },
    {
        name: "Il Molo",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: true,
        hasPoorPricerange: false,
        hasBurger: false,
        hasFish: false,
        hasMeat: true,
        hasPizza: true,
        hasSushi: false,
        hasVeg: true
    },
    {
        name: "YI'S SUSHI & CAFÉ",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: true,
        hasPoorPricerange: false,
        hasBurger: false,
        hasFish: true,
        hasMeat: false,
        hasPizza: false,
        hasSushi: true,
        hasVeg: true
    },
    {
        name: "Stories",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: true,
        hasPoorPricerange: false,
        hasBurger: false,
        hasFish: true,
        hasMeat: true,
        hasPizza: false,
        hasSushi: false,
        hasVeg: true
    },
    {
        name: "Nooshi",
        distance: 0,
        hasLuxuryPricerange: false,
        hasMediumPricerange: true,
        hasPoorPricerange: false,
        hasBurger: false,
        hasFish: true,
        hasMeat: true,
        hasPizza: false,
        hasSushi: true,
        hasVeg: true
    }
]